#pragma once
#include <cstdint>
#include <map>

// Full numeric coverage: 0–255
enum class CctalkHeader : uint8_t
{
    Ack = 0,
    ResetDevice = 1,
    RequestCommsStatusVariables = 2,
    ClearCommsStatusVariables = 3,
    RequestCommsRevision = 4,
    Busy = 6,
    RequestServiceStatus = 104,
    DataStream = 105,
    RequestEscrowStatus = 106,
    OperateEscrow = 107,
    RequestEncryptedMonetaryId = 108,
    RequestEncryptedHopperStatus = 109,
    SwitchEncryptionKey = 110,
    RequestEncryptionSupport = 111,
    ReadEncryptedEvents = 112,
    SwitchBaudRate = 113,
    RequestUsbId = 114,
    RequestRealTimeClock = 115,
    ModifyRealTimeClock = 116,
    RequestCashboxValue = 117,
    ModifyCashboxValue = 118,
    RequestHopperBalance = 119,
    ModifyHopperBalance = 120,
    PurgeHopper = 121,
    RequestErrorStatus = 122,
    RequestActivityRegister = 123,
    VerifyMoneyOut = 124,
    PayMoneyOut = 125,
    ClearMoneyCounter = 126,
    RequestMoneyOut = 127,
    RequestMoneyIn = 128,
    ReadBarcodeData = 129,
    RequestIndexedHopperDispenseCount = 130,
    RequestHopperCoinValue = 131,
    EmergencyStopValue = 132,
    RequestHopperPollingValue = 133,
    DispenseHopperValue = 134,
    SetAcceptLimit = 135,
    StoreEncryptionCode = 136,
    SwitchEncryptionCode = 137,
    FinishFirmwareUpgrade = 138,
    BeginFirmwareUpgrade = 139,
    UploadFirmware = 140,
    RequestFirmwareUpgradeCapability = 141,
    FinishBillTableUpgrade = 142,
    BeginBillTableUpgrade = 143,
    UploadBillTables = 144,
    RequestCurrencyRevision = 145,
    OperateBidirectionalMotors = 146,
    PerformStackerCycle = 147,
    ReadOptoVoltages = 148,
    RequestIndividualErrorCounter = 149,
    RequestIndividualAcceptCounter = 150,
    TestLamps = 151,
    RequestBillOperatingMode = 152,
    ModifyBillOperatingMode = 153,
    RouteBill = 154,
    RequestBillPosition = 155,
    RequestCountryScalingFactor = 156,
    RequestBillId = 157,
    ModifyBillId = 158,
    ReadBufferedBillEvents = 159,
    RequestCipherKey = 160,
    PumpRng = 161,
    ModifiyInhibitAndOverrideRegisters = 162,
    TestHopper = 163,
    EnableHopper = 164,
    ModifyVariableSet = 165,
    RequestHopperStatus = 166,
    DispenseHopperCoins = 167,
    RequestHopperDispenseCount = 168,
    RequestAddressMode = 169,
    RequestBaseYear = 170,
    RequestHopperCoin = 171,
    EmergencyStop = 172,
    RequestThermistorReading = 173,
    RequestPayoutFloat = 174,
    ModifyPayoutFloat = 175,
    RequestAlarmCounter = 176,
    HandheldFunction = 177,
    RequestBankSelect = 178,
    ModifyBankSelect = 179,
    RequestSecuritySetting = 180,
    ModifySecuritySetting = 181,
    DownloadCalibrationInfo = 182,
    UploadWindowData = 183,
    RequestCoinId = 184,
    ModifyCoinId = 185,
    RequestPayoutCapacity = 186,
    ModifyPayoutCapacity = 187,
    RequestDefaultSorterPath = 188,
    ModifyDefaultSorterPath = 189,
    KeypadControl = 191,
    RequestBuildCode = 192,
    RequestFraudCounter = 193,
    RequestRejectCounter = 194,
    RequestLastModificationDate = 195,
    RequestCreationDate = 196,
    CalculateRomChecksum = 197,
    CountersToEeprom = 198,
    ConfigurationToEeprom = 199,
    AcmiUnencryptedProductId = 200,
    RequestTeachStatus = 201,
    TeachModeControl = 202,
    DisplayControl = 203,
    MeterControl = 204,
    RequestPayoutAbsoluteCount = 207,
    ModifyPayoutAbsoluteCount = 208,
    RequestSorterPaths = 209,
    ModifySorterPaths = 210,
    PowerManagementControl = 211,
    RequestCoinPosition = 212,
    RequestOptionFlags = 213,
    WriteDataBlock = 214,
    ReadDataBlock = 215,
    RequestDataStorageAvailability = 216,
    RequestPayoutHighLowStatus = 217,
    EnterPinNumber = 218,
    EnterNewPinNumber = 219,
    AcmiEncryptedData = 220,
    RequestSorterOverrideStatus = 221,
    ModifySorterOverrideStatus = 222,
    ModifyEncryptedInhibitAndOverrideRegisters = 223,
    RequestEncryptedProductId = 224,
    RequestAcceptCounter = 225,
    RequestInsertionCounter = 226,
    RequestMasterInhibitStatus = 227,
    ModifyMasterInhibitStatus = 228,
    ReadBufferedCreditOrErrorCodes = 229,
    RequestInhibitStatus = 230,
    ModifyInhibitStatus = 231,
    PerformSelfCheck = 232,
    LatchOutputLines = 233,
    SendDhPublicKey = 234,
    ReadDhPublicKey = 235,
    ReadOptoStates = 236,
    ReadInputLines = 237,
    TestOutputLines = 238,
    OperateMotors = 239,
    TestSolenoids = 240,
    RequestSoftwareRevision = 241,
    RequestSerialNumber = 242,
    RequestDatabaseVersion = 243,
    RequestProductCode = 244,
    RequestEquipmentCategoryId = 245,
    RequestManufacturerId = 246,
    RequestVariableSet = 247,
    RequestStatus = 248,
    RequestPollingPriority = 249,
    AddressRandom = 250,
    AddressChange = 251,
    AddressClash = 252,
    AddressPoll = 253,
    SimplePoll = 254,
    FactorySetupAndTest = 255
};

// Named aliases for headers you actually use
inline std::string CctalkHeaderGetDisplayableName(CctalkHeader header)
{
    static std::map<CctalkHeader, std::string> name_map = {
        {CctalkHeader::Ack, "Ready"},
        {CctalkHeader::ResetDevice, "ResetDevice"},
        {CctalkHeader::RequestCommsStatusVariables, "RequestCommsStatusVariables"},
        {CctalkHeader::ClearCommsStatusVariables, "ClearCommsStatusVariables"},
        {CctalkHeader::RequestCommsRevision, "RequestCommsRevision"},
        {CctalkHeader::Busy, "Busy"},
        {CctalkHeader::RequestServiceStatus, "RequestServiceStatus"},
        {CctalkHeader::DataStream, "DataStream"},
        {CctalkHeader::RequestEscrowStatus, "RequestEscrowStatus"},
        {CctalkHeader::OperateEscrow, "OperateEscrow"},
        {CctalkHeader::RequestEncryptedMonetaryId, "RequestEncryptedMonetaryId"},
        {CctalkHeader::RequestEncryptedHopperStatus, "RequestEncryptedHopperStatus"},
        {CctalkHeader::SwitchEncryptionKey, "SwitchEncryptionKey"},
        {CctalkHeader::RequestEncryptionSupport, "RequestEncryptionSupport"},
        {CctalkHeader::ReadEncryptedEvents, "eadEncryptedEvents"},
        {CctalkHeader::SwitchBaudRate, "SwitchBaudRate"},
        {CctalkHeader::RequestUsbId, "RequestUsbId"},
        {CctalkHeader::RequestRealTimeClock, "RequestRealTimeClock"},
        {CctalkHeader::ModifyRealTimeClock, "ModifyRealTimeClock"},
        {CctalkHeader::RequestCashboxValue, "RequestCashboxValue"},
        {CctalkHeader::ModifyCashboxValue, "ModifyCashboxValue"},
        {CctalkHeader::RequestHopperBalance, "RequestHopperBalance"},
        {CctalkHeader::ModifyHopperBalance, "ModifyHopperBalance"},
        {CctalkHeader::PurgeHopper, "PurgeHopper"},
        {CctalkHeader::RequestErrorStatus, "RequestErrorStatus"},
        {CctalkHeader::RequestActivityRegister, "RequestActivityRegister"},
        {CctalkHeader::VerifyMoneyOut, "VerifyMoneyOut"},
        {CctalkHeader::PayMoneyOut, "PayMoneyOut"},
        {CctalkHeader::ClearMoneyCounter, "ClearMoneyCounter"},
        {CctalkHeader::RequestMoneyOut, "RequestMoneyOut"},
        {CctalkHeader::RequestMoneyIn, "RequestMoneyIn"},
        {CctalkHeader::ReadBarcodeData, "ReadBarcodeData"},
        {
            CctalkHeader::RequestIndexedHopperDispenseCount,
            "RequestIndexedHopperDispenseCount"
        },
        {CctalkHeader::RequestHopperCoinValue, "RequestHopperCoinValue"},
        {CctalkHeader::EmergencyStopValue, "EmergencyStopValue"},
        {CctalkHeader::RequestHopperPollingValue, "RequestHopperPollingValue"},
        {CctalkHeader::DispenseHopperValue, "DispenseHopperValue"},
        {CctalkHeader::SetAcceptLimit, "SetAcceptLimit"},
        {CctalkHeader::StoreEncryptionCode, "StoreEncryptionCode"},
        {CctalkHeader::SwitchEncryptionCode, "SwitchEncryptionCode"},
        {CctalkHeader::FinishFirmwareUpgrade, "FinishFirmwareUpgrade"},
        {CctalkHeader::BeginFirmwareUpgrade, "BeginFirmwareUpgrade"},
        {CctalkHeader::UploadFirmware, "UploadFirmware"},
        {
            CctalkHeader::RequestFirmwareUpgradeCapability,
            "RequestFirmwareUpgradeCapability"
        },
        {CctalkHeader::FinishBillTableUpgrade, "FinishBillTableUpgrade"},
        {CctalkHeader::BeginBillTableUpgrade, "BeginBillTableUpgrade"},
        {CctalkHeader::UploadBillTables, "UploadBillTables"},
        {CctalkHeader::RequestCurrencyRevision, "RequestCurrencyRevision"},
        {CctalkHeader::OperateBidirectionalMotors, "OperateBidirectionalMotors"},
        {CctalkHeader::PerformStackerCycle, "PerformStackerCycle"},
        {CctalkHeader::ReadOptoVoltages, "ReadOptoVoltages"},
        {
            CctalkHeader::RequestIndividualErrorCounter,
            "RequestIndividualErrorCounter"
        },
        {
            CctalkHeader::RequestIndividualAcceptCounter,
            "RequestIndividualAcceptCounter"
        },
        {CctalkHeader::TestLamps, "TestLamps"},
        {CctalkHeader::RequestBillOperatingMode, "RequestBillOperatingMode"},
        {CctalkHeader::ModifyBillOperatingMode, "ModifyBillOperatingMode"},
        {CctalkHeader::RouteBill, "RouteBill"},
        {CctalkHeader::RequestBillPosition, "RequestBillPosition"},
        {CctalkHeader::RequestCountryScalingFactor, "RequestCountryScalingFactor"},
        {CctalkHeader::RequestBillId, "RequestBillId"},
        {CctalkHeader::ModifyBillId, "ModifyBillId"},
        {CctalkHeader::ReadBufferedBillEvents, "ReadBufferedBillEvents"},
        {CctalkHeader::RequestCipherKey, "RequestCipherKey"},
        {CctalkHeader::PumpRng, "PumpRng"},
        {
            CctalkHeader::ModifiyInhibitAndOverrideRegisters,
            "ModifiyInhibitAndOverrideRegisters"
        },
        {CctalkHeader::TestHopper, "TestHopper"},
        {CctalkHeader::EnableHopper, "EnableHopper"},
        {CctalkHeader::ModifyVariableSet, "ModifyVariableSet"},
        {CctalkHeader::RequestHopperStatus, "RequestHopperStatus"},
        {CctalkHeader::DispenseHopperCoins, "DispenseHopperCoins"},
        {CctalkHeader::RequestHopperDispenseCount, "RequestHopperDispenseCount"},
        {CctalkHeader::RequestAddressMode, "RequestAddressMode"},
        {CctalkHeader::RequestBaseYear, "RequestBaseYear"},
        {CctalkHeader::RequestHopperCoin, "RequestHopperCoin"},
        {CctalkHeader::EmergencyStop, "EmergencyStop"},
        {CctalkHeader::RequestThermistorReading, "RequestThermistorReading"},
        {CctalkHeader::RequestPayoutFloat, "RequestPayoutFloat"},
        {CctalkHeader::ModifyPayoutFloat, "ModifyPayoutFloat"},
        {CctalkHeader::RequestAlarmCounter, "RequestAlarmCounter"},
        {CctalkHeader::HandheldFunction, "HandheldFunction"},
        {CctalkHeader::RequestBankSelect, "RequestBankSelect"},
        {CctalkHeader::ModifyBankSelect, "ModifyBankSelect"},
        {CctalkHeader::RequestSecuritySetting, "RequestSecuritySetting"},
        {CctalkHeader::ModifySecuritySetting, "ModifySecuritySetting"},
        {CctalkHeader::DownloadCalibrationInfo, "DownloadCalibrationInfo"},
        {CctalkHeader::UploadWindowData, "UploadWindowData"},
        {CctalkHeader::RequestCoinId, "RequestCoinId"},
        {CctalkHeader::ModifyCoinId, "ModifyCoinId"},
        {CctalkHeader::RequestPayoutCapacity, "RequestPayoutCapacity"},
        {CctalkHeader::ModifyPayoutCapacity, "ModifyPayoutCapacity"},
        {CctalkHeader::RequestDefaultSorterPath, "RequestDefaultSorterPath"},
        {CctalkHeader::ModifyDefaultSorterPath, "ModifyDefaultSorterPath"},
        {CctalkHeader::KeypadControl, "KeypadControl"},
        {CctalkHeader::RequestBuildCode, "RequestBuildCode"},
        {CctalkHeader::RequestFraudCounter, "RequestFraudCounter"},
        {CctalkHeader::RequestRejectCounter, "RequestRejectCounter"},
        {CctalkHeader::RequestLastModificationDate, "RequestLastModificationDate"},
        {CctalkHeader::RequestCreationDate, "RequestCreationDate"},
        {CctalkHeader::CalculateRomChecksum, "CalculateRomChecksum"},
        {CctalkHeader::CountersToEeprom, "CountersToEeprom"},
        {CctalkHeader::ConfigurationToEeprom, "ConfigurationToEeprom"},
        {CctalkHeader::AcmiUnencryptedProductId, "AcmiUnencryptedProductId"},
        {CctalkHeader::RequestTeachStatus, "RequestTeachStatus"},
        {CctalkHeader::TeachModeControl, "TeachModeControl"},
        {CctalkHeader::DisplayControl, "DisplayControl"},
        {CctalkHeader::MeterControl, "MeterControl"},
        {CctalkHeader::RequestPayoutAbsoluteCount, "RequestPayoutAbsoluteCount"},
        {CctalkHeader::ModifyPayoutAbsoluteCount, "ModifyPayoutAbsoluteCount"},
        {CctalkHeader::RequestSorterPaths, "RequestSorterPaths"},
        {CctalkHeader::ModifySorterPaths, "ModifySorterPaths"},
        {CctalkHeader::PowerManagementControl, "PowerManagementControl"},
        {CctalkHeader::RequestCoinPosition, "RequestCoinPosition"},
        {CctalkHeader::RequestOptionFlags, "RequestOptionFlags"},
        {CctalkHeader::WriteDataBlock, "WriteDataBlock"},
        {CctalkHeader::ReadDataBlock, "ReadDataBlock"},
        {
            CctalkHeader::RequestDataStorageAvailability,
            "RequestDataStorageAvailability"
        },
        {CctalkHeader::RequestPayoutHighLowStatus, "RequestPayoutHighLowStatus"},
        {CctalkHeader::EnterPinNumber, "EnterPinNumber"},
        {CctalkHeader::EnterNewPinNumber, "EnterNewPinNumber"},
        {CctalkHeader::AcmiEncryptedData, "AcmiEncryptedData"},
        {CctalkHeader::RequestSorterOverrideStatus, "RequestSorterOverrideStatus"},
        {CctalkHeader::ModifySorterOverrideStatus, "ModifySorterOverrideStatus"},
        {
            CctalkHeader::ModifyEncryptedInhibitAndOverrideRegisters,
            "ModifyEncryptedInhibitAndOverrideRegisters"
        },
        {CctalkHeader::RequestEncryptedProductId, "RequestEncryptedProductId"},
        {CctalkHeader::RequestAcceptCounter, "RequestAcceptCounter"},
        {CctalkHeader::RequestInsertionCounter, "RequestInsertionCounter"},
        {CctalkHeader::RequestMasterInhibitStatus, "RequestMasterInhibitStatus"},
        {CctalkHeader::ModifyMasterInhibitStatus, "ModifyMasterInhibitStatus"},
        {
            CctalkHeader::ReadBufferedCreditOrErrorCodes,
            "ReadBufferedCreditOrErrorCodes"
        },
        {CctalkHeader::RequestInhibitStatus, "RequestInhibitStatus"},
        {CctalkHeader::ModifyInhibitStatus, "ModifyInhibitStatus"},
        {CctalkHeader::PerformSelfCheck, "PerformSelfCheck"},
        {CctalkHeader::LatchOutputLines, "LatchOutputLines"},
        {CctalkHeader::SendDhPublicKey, "SendDhPublicKey"},
        {CctalkHeader::ReadDhPublicKey, "ReadDhPublicKey"},
        {CctalkHeader::ReadOptoStates, "ReadOptoStates"},
        {CctalkHeader::ReadInputLines, "ReadInputLines"},
        {CctalkHeader::TestOutputLines, "TestOutputLines"},
        {CctalkHeader::OperateMotors, "OperateMotors"},
        {CctalkHeader::TestSolenoids, "TestSolenoids"},
        {CctalkHeader::RequestSoftwareRevision, "RequestSoftwareRevision"},
        {CctalkHeader::RequestSerialNumber, "RequestSerialNumber"},
        {CctalkHeader::RequestDatabaseVersion, "RequestDatabaseVersion"},
        {CctalkHeader::RequestProductCode, "RequestProductCode"},
        {CctalkHeader::RequestEquipmentCategoryId, "RequestEquipmentCategoryId"},
        {CctalkHeader::RequestManufacturerId, "RequestManufacturerId"},
        {CctalkHeader::RequestVariableSet, "RequestVariableSet"},
        {CctalkHeader::RequestStatus, "RequestStatus"},
        {CctalkHeader::RequestPollingPriority, "RequestPollingPriority"},
        {CctalkHeader::AddressRandom, "AddressRandom"},
        {CctalkHeader::AddressChange, "AddressChange"},
        {CctalkHeader::AddressClash, "AddressClash"},
        {CctalkHeader::AddressPoll, "AddressPoll"},
        {CctalkHeader::SimplePoll, "SimplePoll"},
        {CctalkHeader::FactorySetupAndTest, "FactorySetupAndTest"},
    };

    try
    {
        return name_map.at(header);
    }
    catch (const std::exception& e)
    {
        return "Unknown";
    }
}
